[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://taskmaster-app.duckdns.org/:splat"
  status = 200
  force = true
  headers = { 
    "X-Forwarded-Host" = "taskmastertracker.netlify.app",
    "Access-Control-Allow-Origin" = "https://taskmastertracker.netlify.app",
    "Access-Control-Allow-Credentials" = "true"
  }