services:
  db:
    build:
      context: ./db-init
      dockerfile: Dockerfile
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_cron"
      - "-c"
      - "cron.database_name=taskmaster"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "$PG_PASSWORD"
      POSTGRES_DB: taskmaster
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init/:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
      - meilisearch
    networks:
      - app-network
    volumes:
      - ./backend/uploads:/app/uploads # Mount uploads directory

  meilisearch:
    image: getmeili/meilisearch:latest
    env_file:
      - ./.env
    environment:
      MEILI_ENV: production
      MEILI_MASTER_KEY: "$MEILISEARCH_API_KEY"
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "$PG_PASSWORD"
    ports:
      - "5050:80" # Comment out for security unless needed
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:
  meilisearch_data:

networks:
  app-network:
