# docker-compose.prod.yml
services:
  db:
    build:
      context: ./db-init
      dockerfile: Dockerfile
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_cron"
      - "-c"
      - "cron.database_name=taskmaster"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "your_secure_password" # Replace with a secure password
      POSTGRES_DB: taskmaster
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init/:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
      - meilisearch
    networks:
      - app-network

  meilisearch:
    image: getmeili/meilisearch:latest
    env_file:
      - ./.env
    environment:
      MEILI_ENV: production
      MEILI_MASTER_KEY: "$MEILISEARCH_API_KEY"
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "$PGADMIN_PASSWORD" # Replace with a secure password
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:
  meilisearch_data:

networks:
  app-network:
