services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: taskmaster
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:root123@db:5432/taskmaster
      PORT: 5000
    depends_on:
      - db
    networks:
      - app-network
    command: node app.js

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    command: nginx -g 'daemon off;'

volumes:
  db_data:

networks:
  app-network:
