services:
  db:
    build:
      context: ./db-init
      dockerfile: Dockerfile
    command: ["postgres", "-c", "shared_preload_libraries=pg_cron", "-c", "cron.database_name=taskmaster"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: taskmaster
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      target: builder # Use 'builder' stage for development; remove for production
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:root123@db:5432/taskmaster
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app # Mount code for development
      - /app/node_modules # Anonymous volume to prevent issues with node_modules
    depends_on:
      - db
    networks:
      - app-network
    command: nodemon app.js --config nodemon.json # Use nodemon for development; change to 'node app.js' for production

  frontend:
    build:
      context: ./frontend
      target: builder # Use 'builder' stage for development; remove for production
    ports:
      - "5173:5173" # Change to "80:80" for production
    volumes:
      - ./frontend:/app # Mount code for development
      - /app/node_modules # Anonymous volume
    depends_on:
      - backend
    networks:
      - app-network
    command: npm run dev # Use development server; remove for production

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
